config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :likes, only: [:create]
      resources :comments, only: [:new, :create, :destroy]
    end
  end
  root "users#index"

  #API routes
  namespace :api do
    resources :users, only: [:show] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, :all
    can :create, [Comment, Post]
    if user.role == 'admin'
      can :manage, :all
    else
      can :destroy, Comment, author: user
      can :destroy, Post, author: user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post

  after_save :update_comments_counter

  # updates the comments_counter for a post
  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_likes_counter

  # updates the likes_counter for a post
  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250, too_long: '%<count>s characters is the maximun allowed' }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  after_save :update_posts_counter

  # Updates the posts counter for a user
  def update_posts_counter
    author.increment!(:posts_counter)
  end

  # Returns the 5 most recent comments for a given post
  def recent_comments
    comments.order('created_at Desc').limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, allow_nil: true }

  # Returns the 3 most recent posts for a given user
  def recent_three_posts
    posts.order('created_at Desc').limit(3)
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  # GET http://localhost/api/users/:user_id/posts/:post_id/comments
  def index
    @comments = Comment.where(post_id: params[:post_id])

    if @comments
      render json: @comments.to_json(only: [:id, :user_id, :text])
      # render json: { status: 'Success', data: @comments }
    else
      render json: { status: 'Error', data: @comments.errors }
    end
  end

  # POST http://localhost/api/users/:user_id/posts/:post_id/comments
  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.author = @user

    if @comment.save
      render json: @comment.to_json, status: :ok
    else
      render json: { status: 'Not Created', data: @comments.errors }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  load_and_authorize_resource except: %i[index show]

  # GET http://localhost/api/users/:user_id/posts
  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(comments: [:author]).where(author_id: params[:user_id])

    if @posts
      # render json: @posts.to_json, status: :ok
      render json: @posts.to_json(only: [:id, :title, :text, :comments_counter, :likes_counter])
    else
      render json: { status: 'Error', errors: @posts.errors }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :bio, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :bio, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.author = @user
    if @comment.save
      flash[:success] = 'Comment created successfully'
      redirect_to user_post_path(@user, @post)
    else
      flash.now[:errors] = 'Error: Comment could not be saved'
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @user = @post.author

    @comment.destroy
    redirect_to user_posts_path(@user), notice: 'Comment was successfully deleted'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @like = Like.new(user_id: @user.id, post_id: @post.id)
    return unless @like.save

    redirect_to user_post_path(@user.id, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # To ensure authorization happens on every action added to your controller
  # check_authorization
  load_and_authorize_resource except: %i[index show]

  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(comments: [:author]).where(author_id: params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.new(post_params)
    if @post.save
      redirect_to user_posts_path(@user)
    else
      flash.now[:errors] = 'Invalid post!'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @user = @post.author

    @post.destroy
    redirect_to user_posts_path(@user), notice: 'Post was successfully deleted'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.recent_three_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%= form_with model: [@user, @post, @comment], url: user_post_comments_path do |f| %>
  <div>
    <%= f.label :text, required: true %>
    <%= f.text_field :text, autofocus: true, required: true %>
  </div>
  <div>
    <%= f.submit "Comment" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<main class="post-index">
  <%= button_to("Log Out", destroy_user_session_path, method: :delete) %>
  <%= button_to("Home", root_path, method: :get) %>
  <%= render 'shared/user', user: @user %>
  <%= link_to "Add a Post...", new_user_post_path(@user) %>
  <% @posts.reverse_each do |post| %>
    <div class="post-details">
      <%= render 'shared/post', post: post %>

      <div>
        <%= link_to "Add Comment", new_user_post_comment_path(@user, post) %>
        <%= form_with url: user_post_likes_path(post.author.id, post.id) do |form| %>
          <%= form.submit 'Like' %>
        <% end %>
      </div>

      <div class="comment-container">
        <% post.recent_comments.reverse_each do |comment| %>
          <%= render 'shared/comment', comment: comment %>

          <% if can? :destroy, comment %>
            <%= form_for [@user, post, comment], url: user_post_comment_path(post.author, post, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } do |f| %>
              <%= f.submit "Delete Comment" %>
            <% end %>
          <% end %>

        <% end %>
      </div>
    </div>
  <% end %>
</main>

app/views/posts/new.html.erb
<div>
  <%= form_with model: @post, url: user_posts_path(@user) do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title, autofocus: true, required: true %>
    <%= form.label :text %>
    <%= form.text_field :text, autofocus: true, required: true %>
    <%= form.submit "Post" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<main class="post-show">
  <%= button_to("Log Out", destroy_user_session_path, method: :delete) %>
  <%= button_to("Home", root_path, method: :get) %>
  <div class="post-in-show">
    <div><%= @post.title %> by <%= @post.author.name %></div>
    <div>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></div>
    <p><%= @post.text %></p>

  </div>
  <div class="comment-container">
    <% @post.comments.each do |comment| %>
      <%= render 'shared/comment', comment: comment %>

      <% if can? :destroy, comment %>
        <%= form_for [@user, @post, comment], url: user_post_comment_path(@post.author, @post, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } do |f| %>
          <%= f.submit "Delete Comment" %>
        <% end %>
      <% end %>

    <% end %>
  </div>
</main>

app/views/shared/_comment.html.erb
<p><%= comment.author.name %>: <%= comment.text%></p>

app/views/shared/_delete_button.html.erb
<% if can? :destroy, model%>
    <%= button_to "Delete", url, method: :delete,  class: 'delete-btn'%>
<%end %>

app/views/shared/_post.html.erb
<%=link_to user_post_path(@user, post) do %>
  <div class="post">
    <h3><%= post.title %></h3>
    <p><%= post.text %></p>
    <p>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %> </p>
  </div>
<% end %>

<% if can? :destroy, post %>
  <%= form_for [@user, post], url: user_post_path(@user, post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } do |f| %>
    <%= f.submit "Delete Post" %>
  <% end %>
<% end %>

app/views/shared/_user.html.erb
<%= link_to user_path(user) do %>
  <div class="user-container">
    <div class='image-container'>
      <img src="<%= user.photo %>" alt="<%= user.name %>" width="150" height="150" />
    </div>
    <div class='text-container'>
      <h2><%= user.name %></h2>
      <p>Number of posts: <%= user.posts_counter %></p>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<main class="user-index">
  <%= button_to("Log Out", destroy_user_session_path, method: :delete) %>
  <% @users.each do |user| %>
    <%= render 'shared/user', user: user %>
  <% end %>
</main>

app/views/users/show.html.erb
<main class="user-show">
  <%= button_to("Log Out", destroy_user_session_path, method: :delete) %>
  <%= button_to("Home", root_path, method: :get) %>
  <%= render 'shared/user', user: @user %>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
  <div class="bio">
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
  </div>

  <%= link_to "Add a Post...", new_user_post_path(@user) %>

  <% @recent_posts.each do |post| %>
    <%= render 'shared/post', post: post %>
  <% end %>
  <button> <%= link_to 'See all posts', user_posts_path(@user) %></button>
</main>